version: "2"
services:
  db:
    image: latest
    build: postgres
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
