version: "2"
services:
  db:
    image: latest
    build: postgres
    volume:
    - postgres:/var/lib/pgsql
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
